"""Sweep runner: iterates query × cell × combo × seed and writes results.jsonl.

    python ablation/sweep.py -c configs/luby_sweet_spot.toml
    python ablation/sweep.py -c ... --gucs '{"depth": [2,3,4], "luby": {"start_budget": [20,40]}}'
    python ablation/sweep.py -c ... --dry-run
"""

from __future__ import annotations

import argparse
import concurrent.futures as cf
import contextlib
import datetime as dt
import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
import tomllib
from dataclasses import asdict, dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import lib

_REPO_ROOT = Path(__file__).resolve().parent.parent


def _default_pgbin() -> str:
    """Parent of the `pg_ctl` on PATH, or empty string to mean 'use PATH'."""
    import shutil

    found = shutil.which("pg_ctl")
    return str(Path(found).parent) if found else ""


DEFAULT_PGBIN = os.environ.get("PGBIN") or _default_pgbin()
DEFAULT_PGDATA = os.environ.get("PGDATA", "")  # required at sweep time; see _require_pg
DEFAULT_PGLOG = os.environ.get("PGLOG", "/tmp/mcts_extreme_pg.log")
DEFAULT_DOCKER_CONTAINER = os.environ.get("DOCKER_CONTAINER", "")
DEFAULT_PGUSER = os.environ.get("PGUSER", "postgres")
DEFAULT_JOB_DIR = str(_REPO_ROOT / "source" / "resource" / "imdb_original_queries")
DEFAULT_DB = os.environ.get("DB", "imdb")
DEFAULT_DROP_CACHES = _REPO_ROOT / "ablation" / "drop_caches.sh"


def geqo_seed_value(seed: int) -> str:
    """Map integer experiment seeds to PostgreSQL's geqo_seed range."""
    phi_conjugate = 0.6180339887498949
    value = (int(seed) * phi_conjugate) % 1.0
    if value <= 0.0:
        value = 1.0
    return f"{value:.17g}"


# For baselines we run ONE cell per (query, seed); reward/agg axes don't apply.
BASELINE_CONFIGS = {
    "dp": "ablation/baseline_dp.sql",
    "geqo": "ablation/baseline_geqo.sql",
}

# Symbolic source names → in-repo query dirs.  `imdb_original_queries` may
# later be renamed to `job`; the lookup key stays stable either way.
KNOWN_SOURCES = {
    "job": str(_REPO_ROOT / "source" / "resource" / "imdb_original_queries"),
    "jobcomplex": str(_REPO_ROOT / "source" / "resource" / "job_complex"),
    "imdb-ceb": str(
        _REPO_ROOT / "source" / "resource" / "imdb-ceb" / "queries" / "rel9_seed42_200_flat"
    ),
    # TPC-H: 22 queries (q1..q22) generated by pg_tpch/run_tpch.sh and copied here.
    # Run against the `tpch` database (set db="tpch" in the config or DB=tpch env).
    "tpch": str(_REPO_ROOT / "source" / "resource" / "tpch"),
}

# --- config ---


@dataclass
class ExperimentConfig:
    name: str
    description: str
    run_group: str
    queries: list[str]
    reward_modes: list[str]
    uct_aggregations: list[str]
    configs: list[str]  # subset of {"luby","single"}
    n_seeds: int
    template_luby: str
    template_single: str
    gucs: dict[str, dict[str, float | int | str]]
    sources: list[str]  # ordered list of source names / paths
    mcts_cells: list[dict]
    # Runtime knobs (env-overridable).
    pgbin: str = DEFAULT_PGBIN
    pgdata: str = DEFAULT_PGDATA
    pglog: str = DEFAULT_PGLOG
    docker_container: str = DEFAULT_DOCKER_CONTAINER
    pguser: str = DEFAULT_PGUSER
    db: str = DEFAULT_DB
    measurement: str = "full_protocol"


def resolve_source_dir(source: str) -> Path:
    """Turn a source name or path into a directory containing `<q>.sql` files."""
    return Path(KNOWN_SOURCES.get(source, source))


def parse_sources(raw) -> list[str]:
    """Accept str (single or comma-sep) or list[str]; return list."""
    if raw is None:
        return ["job"]
    if isinstance(raw, list):
        return [str(x) for x in raw if str(x).strip()]
    s = str(raw)
    if "," in s:
        return [t.strip() for t in s.split(",") if t.strip()]
    return [s.strip()]


def find_query_source(query: str, sources: list[str]) -> Path | None:
    """If query has a `source:name` prefix, use it.  Else search each source
    dir in declaration order and return the first hit.  None if not found.
    """
    if ":" in query:
        src, name = query.split(":", 1)
        d = resolve_source_dir(src)
        f = d / f"{name}.sql"
        return f if f.is_file() else None
    for src in sources:
        d = resolve_source_dir(src)
        f = d / f"{query}.sql"
        if f.is_file():
            return f
    return None


def load_config(path: Path) -> ExperimentConfig:
    raw = tomllib.loads(path.read_text())
    # Field history: `job_dir` -> `source` (single) -> `sources` (list).
    sources = parse_sources(raw.get("sources") or raw.get("source") or raw.get("job_dir"))
    return ExperimentConfig(
        name=raw["name"],
        description=raw.get("description", ""),
        run_group=str(raw.get("run_group") or raw.get("group") or ""),
        queries=list(raw["queries"]),
        reward_modes=list(raw["reward_modes"]),
        uct_aggregations=list(raw["uct_aggregations"]),
        configs=list(raw.get("configs", ["luby", "single"])),
        n_seeds=int(raw["n_seeds"]),
        template_luby=raw["template_luby"],
        template_single=raw["template_single"],
        gucs={
            "shared": dict(raw.get("gucs", {}).get("shared", {})),
            "luby": dict(raw.get("gucs", {}).get("luby", {})),
            "single": dict(raw.get("gucs", {}).get("single", {})),
        },
        sources=parse_sources(os.environ.get("JOB_DIR")) if os.environ.get("JOB_DIR") else sources,
        mcts_cells=list(raw.get("mcts_cells", [])),
        pgbin=DEFAULT_PGBIN,
        pgdata=DEFAULT_PGDATA,
        pglog=DEFAULT_PGLOG,
        docker_container=DEFAULT_DOCKER_CONTAINER,
        pguser=DEFAULT_PGUSER,
        # Precedence: DB env var (ad-hoc override) > config `db` > "imdb" default.
        db=os.environ.get("DB") or str(raw.get("db", "imdb")),
        measurement=str(raw.get("measurement", "full_protocol")),
    )


# --- GUC override + SQL templating ---

# Luby restart-sequence weights.  weights[k-1] = luby(k); the cumulative sum
# of these gives the total iter cap when start_budget is per-phase.
_LUBY_WEIGHTS = (1, 1, 2, 1, 1, 2, 4, 1, 1, 2, 1, 1, 2, 4, 8, 1)


def _sort_mixed_key(value):
    """Sort key for mixed int/str sequences: numerics first, natural order within group."""
    return (isinstance(value, str), value)


def luby_cap(start_budget: int, phases: int) -> int:
    """start_budget × sum_{k=1..phases} luby(k); capped at len(_LUBY_WEIGHTS)."""
    if phases <= 0:
        return 0
    phases = min(phases, len(_LUBY_WEIGHTS))
    return start_budget * sum(_LUBY_WEIGHTS[:phases])


_SET_LINE_RE_TPL = r"^(\s*SET\s+mcts_extreme\.{name}\s*=\s*)[^;]+;"


def _sub_guc(sql: str, name: str, value) -> str:
    if isinstance(value, bool):
        value = "on" if value else "off"
    elif isinstance(value, str) and not value.startswith("'"):
        value = "'" + value.replace("'", "''") + "'"
    pat = re.compile(_SET_LINE_RE_TPL.format(name=re.escape(name)), re.M)
    return pat.sub(rf"\g<1>{value};", sql)


def render_sql_template(template_path: Path, gucs: dict) -> str:
    """Read template SQL, apply every GUC override.

    ``gucs`` is a flat dict (already merged: shared <- config-specific
    <- CLI overrides).  Unknown keys are silently ignored — the template
    may not contain a SET line for every possible GUC.
    """
    sql = template_path.read_text()
    for name, value in gucs.items():
        sql = _sub_guc(sql, name, value)
    return sql


def repo_path(path: str | Path) -> Path:
    p = Path(path)
    if p.is_absolute() or p.exists():
        return p
    return _REPO_ROOT / p


# Path-segment abbreviations for combo_id slugs; unknown keys fall back to first 3 chars.
_PATH_ABBREV = {
    "depth": "d",
    "search_algorithm": "alg",
    "top_k": "tk",
    "plan_shape": "k",
    "expand_strategy": "exp",
    "patience": "pat",
    "rollouts_per_leaf": "rpl",
    "full_budget": "fb",
    "exploration_constant": "ec",
    "start_budget": "sb",
    "phases": "ph",
    "luby": "L",
    "single": "S",
}


def _abbrev(k: str) -> str:
    return _PATH_ABBREV.get(k, k[:3])


def _combo_value_slug(path: tuple[str, ...], value) -> str:
    if path and path[-1] == "full_budget":
        if isinstance(value, bool):
            enabled = value
        else:
            enabled = str(value).strip().lower() in {"1", "true", "t", "yes", "y", "on"}
        return "full" if enabled else "flex"
    if path and path[-1] == "search_algorithm":
        return {
            "mcts": "mcts",
            "saio": "saio",
            "iterative_improvement": "ii",
            "ii": "ii",
        }.get(str(value), str(value))
    if path and path[-1] == "expand_strategy":
        return {
            "mixed_025": "m025",
            "mixed_050": "m050",
            "selectivity": "sel",
        }.get(str(value), str(value))
    return str(value)


def expand_gucs_grid(gucs: dict) -> tuple[list[dict], list[tuple[str, ...]]]:
    """Cartesian-product over list-valued leaves.  Scalar-only input → one no-op combo.
    Returns (combos, varying_paths)."""
    leaves: list[tuple[tuple[str, ...], list]] = []

    def walk(d: dict, prefix: tuple[str, ...]) -> None:
        for k, v in d.items():
            if isinstance(v, dict):
                walk(v, (*prefix, k))
            elif isinstance(v, list):
                leaves.append(((*prefix, k), list(v)))
            else:
                leaves.append(((*prefix, k), [v]))

    walk(gucs, ())
    if not leaves:
        return [{}], []

    import itertools

    varying = [p for p, vals in leaves if len(vals) > 1]
    combos: list[dict] = []
    for choice in itertools.product(*[v for _, v in leaves]):
        combo: dict = {}
        for (path, _), val in zip(leaves, choice, strict=False):
            cur = combo
            for k in path[:-1]:
                cur = cur.setdefault(k, {})
            cur[path[-1]] = val
        combos.append(combo)
    return combos, varying


def combo_id(combo: dict, varying: list[tuple[str, ...]]) -> str:
    """Slug like `d3_ec1.41_Lsb80` from the varying paths; empty when grid is degenerate."""
    if not varying:
        return ""
    parts = []
    for path in varying:
        cur: object = combo
        for k in path:
            if isinstance(cur, dict):
                cur = cur.get(k)
            else:
                cur = None
                break
        slug_key = "_".join(_abbrev(k) for k in path)
        parts.append(f"{slug_key}{_combo_value_slug(path, cur)}")
    return "_".join(parts)


def apply_gucs(cfg: ExperimentConfig, cli_gucs: dict) -> tuple[dict, dict]:
    """Merge config + CLI gucs for each MCTS config.  Precedence: shared <
    config-specific < CLI.  CLI may be flat (`{"depth":5}` applies to both)
    or nested (`{"luby":{"phases":12}}` applies to luby only).

    `single.start_budget` is auto-derived from luby_cap unless explicitly set
    anywhere — keeps total iter budget matched without forcing two knobs to
    move together.
    """
    flat_cli = {k: v for k, v in cli_gucs.items() if not isinstance(v, dict)}
    nested_cli = {k: v for k, v in cli_gucs.items() if isinstance(v, dict)}

    def merge(which: str) -> dict:
        out = dict(cfg.gucs["shared"])
        out.update(cfg.gucs.get(which, {}))
        out.update(flat_cli)
        out.update(nested_cli.get(which, {}))
        return out

    luby_g = merge("luby")
    single_g = merge("single")

    # Was single.start_budget explicitly set anywhere?
    explicit_single_budget = (
        "start_budget" in cfg.gucs.get("single", {})
        or "start_budget" in nested_cli.get("single", {})
        or "start_budget" in flat_cli  # flat applies to both
    )
    if not explicit_single_budget and "start_budget" in luby_g and "phases" in luby_g:
        single_g["start_budget"] = luby_cap(int(luby_g["start_budget"]), int(luby_g["phases"]))

    return luby_g, single_g


# --- shell helpers ---


def _pg(cfg: ExperimentConfig, tool: str) -> str:
    """`<pgbin>/<tool>` when pgbin is set, otherwise rely on PATH."""
    return f"{cfg.pgbin}/{tool}" if cfg.pgbin else tool


def _docker_exec(cfg: ExperimentConfig, *args: str, input_text: str | None = None):
    cmd = ["docker", "exec"]
    if input_text is not None:
        cmd.append("-i")
    cmd.append(cfg.docker_container)
    cmd.extend(args)
    return subprocess.run(cmd, input=input_text, capture_output=True, text=True, check=False)


def restart_cluster(cfg: ExperimentConfig) -> None:
    if cfg.docker_container:
        subprocess.run(
            ["docker", "restart", cfg.docker_container],
            check=True,
            stdout=subprocess.DEVNULL,
        )
        for _ in range(60):
            probe = _docker_exec(cfg, "pg_isready", "-U", cfg.pguser, "-d", cfg.db)
            if probe.returncode == 0:
                return
            time.sleep(1)
        raise subprocess.CalledProcessError(1, ["docker", "exec", cfg.docker_container, "pg_isready"])
    subprocess.run(
        [_pg(cfg, "pg_ctl"), "-D", cfg.pgdata, "-l", cfg.pglog, "restart", "-m", "fast", "-w"],
        check=True,
        stdout=subprocess.DEVNULL,
    )


def drop_os_caches(command: str | None = None) -> None:
    """Drop Linux page cache before a measurement batch.

    The default path uses a tiny root-owned operation.  When the sweep is not
    root, sudo is called with -n so Streamlit launches fail fast if the sudoers
    rule is missing instead of blocking on a password prompt.
    """
    if command:
        cmd = shlex.split(command)
    elif os.geteuid() == 0:
        cmd = [str(DEFAULT_DROP_CACHES)]
    else:
        cmd = ["sudo", "-n", str(DEFAULT_DROP_CACHES)]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)


def ensure_pg_running(cfg: ExperimentConfig) -> bool:
    """Return True if PG is reachable (after starting it if needed); False otherwise.

    Prints actionable diagnostics to stderr on failure so the Streamlit UI's
    launch-log tail shows a real explanation instead of a buried mid-sweep crash.
    """
    if cfg.docker_container:
        probe = _docker_exec(cfg, "pg_isready", "-U", cfg.pguser, "-d", cfg.db)
        if probe.returncode == 0:
            return True
        print(
            f"Docker Postgres not reachable in {cfg.docker_container!r}: "
            f"{(probe.stdout or probe.stderr).strip()}",
            file=sys.stderr,
        )
        try:
            restart_cluster(cfg)
        except subprocess.CalledProcessError as e:
            print(f"docker restart failed for {cfg.docker_container!r}: {e}", file=sys.stderr)
            return False
        return True

    probe = subprocess.run(
        [_pg(cfg, "pg_isready"), "-h", "/tmp", "-d", cfg.db],
        capture_output=True,
        text=True,
        timeout=5,
    )
    if probe.returncode == 0:
        return True

    print(
        f"Postgres not reachable ({probe.stdout.strip() or 'pg_isready rc={probe.returncode}'}); "
        "attempting pg_ctl start...",
        file=sys.stderr,
    )
    try:
        subprocess.run(
            [_pg(cfg, "pg_ctl"), "-D", cfg.pgdata, "-l", cfg.pglog, "start", "-w"],
            check=True,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except subprocess.CalledProcessError as e:
        print(
            f"pg_ctl start failed (rc={e.returncode}):\n"
            f"  stdout: {e.stdout.strip()}\n"
            f"  stderr: {e.stderr.strip()}\n"
            f"Tail of {cfg.pglog}:",
            file=sys.stderr,
        )
        with contextlib.suppress(OSError):
            print(Path(cfg.pglog).read_text()[-2000:], file=sys.stderr)
        print(
            f"\nFix manually then re-launch:\n"
            f"  {_pg(cfg, 'pg_ctl')} -D {cfg.pgdata} -l {cfg.pglog} start",
            file=sys.stderr,
        )
        return False
    except subprocess.TimeoutExpired:
        print(
            f"pg_ctl start timed out after 30s. Check {cfg.pglog} and any stale "
            f"postmaster.pid in {cfg.pgdata}.",
            file=sys.stderr,
        )
        return False
    return True


def build_measure_sql(raw_path: Path, query: str, dst: Path, measurement: str) -> Path:
    if not raw_path.exists():
        raise FileNotFoundError(f"missing query SQL: {raw_path}")
    suffix = "cost" if measurement == "cost_only" else "analyze"
    explain = (
        "EXPLAIN (COSTS on, SUMMARY on)\n"
        if measurement == "cost_only"
        else "EXPLAIN (ANALYZE, BUFFERS, COSTS on, SUMMARY on, TIMING on)\n"
    )
    out = dst / f"{query}.{suffix}.sql"
    out.write_text(explain + raw_path.read_text())
    return out


def build_prewarm_sql(raw_path: Path, query: str, dst: Path) -> Path:
    """EXPLAIN-only (no ANALYZE) variant used to warm pg_statistic + relcache after
    a cluster restart, so every parallel measurement cell sees identical warm state.
    Uses DP planner to keep the warmup deterministic and as cheap as possible."""
    out = dst / f"{query}.prewarm.sql"
    out.write_text(
        "LOAD 'mcts_extreme';\n"
        "SET pg_mcts_extreme.enabled = off;\n"
        "SET mcts_extreme.enabled = off;\n"
        "SET geqo = off;\n"
        "SET geqo_threshold = 64;\n"
        "EXPLAIN " + raw_path.read_text()
    )
    return out


def run_prewarm(cfg: ExperimentConfig, prewarm_sql: Path) -> None:
    """Single non-analyzing EXPLAIN to populate shared_buffers with catalog pages.
    Errors are swallowed — prewarm is best-effort, the measurement runs are what count."""
    if cfg.docker_container:
        _docker_exec(
            cfg,
            "psql",
            "-U",
            cfg.pguser,
            "-d",
            cfg.db,
            "-X",
            "-f",
            "-",
            input_text=prewarm_sql.read_text(),
        )
        return
    subprocess.run(
        [_pg(cfg, "psql"), "-h", "/tmp", "-d", cfg.db, "-X", "-f", str(prewarm_sql)],
        capture_output=True,
        check=False,
    )


def _inline_analyze_sql(sql_file: Path, query_sql: Path) -> str:
    return sql_file.read_text().replace(r"\i :analyze_sql", query_sql.read_text())


# Low-discrepancy Weyl sequence (golden-ratio fractional part).
# Maps integer seed N >= 1 to a distinct, well-spread float in (0, 1),
# suitable for SET geqo_seed which requires range [0.0, 1.0].
_GEQO_SEED_PHI = 0.6180339887498949  # (sqrt(5) - 1) / 2


def geqo_seed_value(seed_int: int) -> float:
    """Return a distinct float in (0, 1) for each positive integer seed."""
    return round((seed_int * _GEQO_SEED_PHI) % 1.0, 12) or 1e-6


def run_psql(
    cfg: ExperimentConfig, sql_file: Path, *, reward: str, agg: str, seed: int, query_sql: Path
) -> str:
    geqo_seed = geqo_seed_value(seed)
    common_vars = [
        "-v", f"reward={reward}",
        "-v", f"agg={agg}",
        "-v", f"seed={seed}",
        "-v", f"geqo_seed={geqo_seed}",
    ]
    if cfg.docker_container:
        result = _docker_exec(
            cfg,
            "psql",
            "-U",
            cfg.pguser,
            "-d",
            cfg.db,
            "-X",
            *common_vars,
            "-f",
            "-",
            input_text=_inline_analyze_sql(sql_file, query_sql),
        )
        return result.stdout + ("\n" + result.stderr if result.stderr else "")
    result = subprocess.run(
        [
            _pg(cfg, "psql"),
            "-h",
            "/tmp",
            "-d",
            cfg.db,
            "-X",
            *common_vars,
            "-v",
            f"geqo_seed={geqo_seed}",
            "-v",
            f"analyze_sql={query_sql}",
            "-f",
            str(sql_file),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout + ("\n" + result.stderr if result.stderr else "")


def cell_dirname(config: str, reward: str, agg: str, cid: str = "") -> str:
    if config in BASELINE_CONFIGS:
        return config
    base = f"{config}__{reward}__{agg}"
    return f"{base}__{cid}" if cid else base


def _sql_basename(config: str, cid: str) -> str:
    return f"{config}__{cid}.sql" if cid else f"{config}.sql"


def _cell_combo(cell: dict) -> dict:
    combo: dict = {}
    for key in (
        "depth",
        "search_algorithm",
        "plan_shape",
        "force_left_tree",
        "top_k",
        "expand_strategy",
        "patience",
        "rollouts_per_leaf",
        "full_budget",
        "exploration_constant",
        "saio_max_iterations",
    ):
        if key in cell:
            combo[key] = cell[key]
    config = cell.get("config", "single")
    if "start_budget" in cell:
        combo.setdefault(config, {})["start_budget"] = cell["start_budget"]
    if "phases" in cell:
        combo.setdefault(config, {})["phases"] = cell["phases"]
    return combo


def _selected_mcts_cells(cfg: ExperimentConfig) -> list[tuple[str, str, str, str, dict]]:
    cells = []
    seen: set[tuple[str, str, str, str]] = set()
    for i, raw in enumerate(cfg.mcts_cells, start=1):
        config = str(raw.get("config", "single"))
        if config in BASELINE_CONFIGS:
            raise ValueError(f"mcts_cells[{i}] uses baseline config {config!r}")
        reward = str(raw["reward"])
        agg = str(raw.get("agg", "best"))
        combo = _cell_combo(raw)
        cid = str(raw.get("combo_id") or combo_id(combo, list(_flatten_paths(combo))))
        ident = (config, reward, agg, cid)
        if ident in seen:
            raise ValueError(f"duplicate mcts cell: {ident}")
        seen.add(ident)
        cells.append((config, reward, agg, cid, combo))
    return cells


def _flatten_paths(d: dict, prefix: tuple[str, ...] = ()):
    for key, value in d.items():
        if isinstance(value, dict):
            yield from _flatten_paths(value, (*prefix, key))
        else:
            yield (*prefix, key)


def init_run_dir(
    cfg: ExperimentConfig, cli_gucs: dict, runs_root: Path, record_env: bool = False
) -> tuple[Path, list[dict], list[tuple[str, ...]]]:
    ts = dt.datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    run_dir = runs_root / f"{ts}-{cfg.name}"
    run_dir.mkdir(parents=True, exist_ok=False)

    try:
        git_rev = (
            subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True,
                text=True,
                check=False,
            ).stdout.strip()
            or "(unknown)"
        )
    except Exception:
        git_rev = "(unknown)"

    selected_cells = _selected_mcts_cells(cfg) if cfg.mcts_cells else []
    if selected_cells:
        combos = [cell[-1] for cell in selected_cells]
        varying = []
    else:
        combos, varying = expand_gucs_grid(cli_gucs)

    md_grid_block: list[str] = []
    if selected_cells:
        md_grid_block.append("## Selected MCTS cells")
    else:
        md_grid_block.append("## Grid axes" if varying else "## GUCs (single point — no grid)")
    if varying:
        md_grid_block.append("```")
        for path in varying:
            vals = sorted({_get_path(c, path) for c in combos}, key=_sort_mixed_key)
            md_grid_block.append(f"{'.'.join(path)} ∈ {vals}")
        md_grid_block.append("```")
        md_grid_block.append(f"\n**{len(combos)} combos** total.\n")

    render_items = (
        [(config, cid, combo) for config, _reward, _agg, cid, combo in selected_cells]
        if selected_cells
        else [("luby", combo_id(combo, varying), combo) for combo in combos]
        + [("single", combo_id(combo, varying), combo) for combo in combos]
    )
    for config, cid, combo in render_items:
        luby_gucs, single_gucs = apply_gucs(cfg, combo)
        if config == "luby":
            gucs = luby_gucs
            sql = render_sql_template(repo_path(cfg.template_luby), gucs)
        elif config == "single":
            gucs = single_gucs
            sql = render_sql_template(repo_path(cfg.template_single), gucs)
        else:
            raise ValueError(f"unknown MCTS config: {config}")
        (run_dir / _sql_basename(config, cid)).write_text(sql)

        md_grid_block.append(f"### combo `{cid or '(single)'}`")
        md_grid_block.append("```")
        md_grid_block.append(f"{config}:")
        md_grid_block.extend(f"  {k} = {v}" for k, v in sorted(gucs.items()))
        md_grid_block.append("```")

    for bname, btemplate in BASELINE_CONFIGS.items():
        src = repo_path(btemplate)
        if src.exists():
            (run_dir / f"{bname}.sql").write_text(src.read_text())

    md = [
        f"# {cfg.name}",
        "",
        cfg.description or "",
        "",
        f"- **Started**: {ts}",
        f"- **Git revision**: `{git_rev}`",
        f"- **Run group**: {cfg.run_group or '(none)'}",
        f"- **n_seeds**: {cfg.n_seeds}",
        f"- **Configs**: {', '.join(cfg.configs)}",
        f"- **Reward modes**: {', '.join(cfg.reward_modes)}",
        f"- **UCT aggregations**: {', '.join(cfg.uct_aggregations)}",
        f"- **Queries** ({len(cfg.queries)}): {', '.join(cfg.queries)}",
        "",
        *md_grid_block,
    ]
    (run_dir / "README.md").write_text("\n".join(md) + "\n")

    # Save the resolved config (config + CLI overrides) for full reproducibility.
    config_dump = asdict(cfg)
    config_dump["cli_gucs"] = cli_gucs
    config_dump["grid_varying"] = [".".join(p) for p in varying]
    config_dump["n_combos"] = len(combos)
    if not record_env:
        # Local-environment knobs (paths, DB user, container) are omitted by
        # default so published runs don't leak them; pass --record-env to keep.
        for _k in ("pgbin", "pgdata", "pglog", "docker_container", "pguser", "db"):
            config_dump.pop(_k, None)
    (run_dir / "config.json").write_text(json.dumps(config_dump, indent=2, default=str))

    lib.write_status(run_dir, lib.STATUS_RUNNING)
    return run_dir, combos, varying


def _get_path(d: dict, path: tuple[str, ...]):
    cur: object = d
    for k in path:
        if isinstance(cur, dict):
            cur = cur.get(k)
        else:
            return None
    return cur


# --- sweep loop ---


def append_jsonl(path: Path, row: dict) -> None:
    # fsync after each row so the streamlit UI sees them as they're written.
    with path.open("a") as f:
        f.write(json.dumps(row, sort_keys=False) + "\n")
        f.flush()
        os.fsync(f.fileno())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run an mcts_extreme ablation sweep.")
    parser.add_argument(
        "-c", "--config", type=Path, required=True, help="Path to .toml experiment config."
    )
    parser.add_argument(
        "-n",
        "--name",
        type=str,
        default=None,
        help="Override experiment name (default: from toml).",
    )
    parser.add_argument(
        "--run-group",
        type=str,
        default=None,
        help="Override UI run group name (default: from toml).",
    )
    parser.add_argument("--seeds", type=int, default=None, help="Override n_seeds.")
    parser.add_argument(
        "--queries", type=str, default=None, help='Override queries, e.g. "27a 27b 33a".'
    )
    parser.add_argument(
        "--rewards",
        type=str,
        default=None,
        help='Override reward maps, e.g. "neg_log norm_neg_log".',
    )
    parser.add_argument(
        "--aggs", type=str, default=None, help='Override UCT aggregations, e.g. "best average".'
    )
    parser.add_argument(
        "--configs", type=str, default=None, help='Override configs to compare, e.g. "luby single".'
    )
    parser.add_argument(
        "--gucs", type=str, default="{}", help="JSON GUC overrides; flat or nested by config name."
    )
    parser.add_argument(
        "--mcts-cells",
        type=str,
        default=None,
        help="JSON list of exact MCTS cells. Overrides TOML [[mcts_cells]]; [] disables them.",
    )
    parser.add_argument(
        "--source",
        type=str,
        default=None,
        help="Query source name (job, jobcomplex) or a directory path.",
    )
    parser.add_argument(
        "--runs-root",
        type=Path,
        default=_REPO_ROOT / "runs",
        help="Where to create the run directory.",
    )
    parser.add_argument(
        "--docker-container",
        type=str,
        default=None,
        help="Run psql/restarts through this Docker container instead of local pg_ctl/psql.",
    )
    parser.add_argument(
        "--pguser",
        type=str,
        default=None,
        help="Database user for Docker psql/pg_isready (default: PGUSER or postgres).",
    )
    parser.add_argument(
        "--measurement",
        choices=("full_protocol", "cost_only"),
        default=None,
        help="full_protocol = EXPLAIN ANALYZE; cost_only = EXPLAIN without execution.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print sweep plan + run dir path, do nothing else."
    )
    parser.add_argument(
        "-j",
        "--parallel",
        type=int,
        default=1,
        help="Max cells to run concurrently per (query, seed) batch. "
        "0 = run all cells in parallel.  1 = sequential (default).",
    )
    parser.add_argument(
        "--prewarm",
        action="store_true",
        help="Run one EXPLAIN-only DP plan after each cluster restart, before launching "
        "parallel cells.  Off by default: empirically the prewarm warms shared_buffers in "
        "a way that occasionally perturbs MCTS plan_cost under parallel load (~1 in 24 "
        "runs in our smoke tests), likely floating-point ordering in cost summation.  "
        "Without prewarm, parallel runs reproduce sequential plan_costs exactly.",
    )
    parser.add_argument(
        "--drop-os-cache",
        action="store_true",
        help="After each cluster restart and before launching the parallel cell batch, "
        "drop Linux OS caches. Non-root runs use `sudo -n ablation/drop_caches.sh`, "
        "so configure passwordless sudo for that helper.",
    )
    parser.add_argument(
        "--drop-cache-command",
        type=str,
        default=os.environ.get("DROP_CACHE_COMMAND"),
        help="Optional command used by --drop-os-cache instead of the default helper. "
        "Parsed with shlex, not through a shell.",
    )
    parser.add_argument(
        "--restart-pg-per-batch",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Restart PostgreSQL before every (query, seed) parallel batch. Enabled by default.",
    )
    parser.add_argument(
        "--clean-per-run",
        action="store_true",
        help="Clean before every individual cell measurement instead of once per "
        "(query, seed) batch. Forces workers=1. Uses --restart-pg-per-batch and "
        "--drop-os-cache settings to decide which cleanup actions to perform.",
    )
    parser.add_argument(
        "--record-env",
        action="store_true",
        help="Record local environment knobs (pgbin, pgdata, pglog, pguser, db, "
        "docker_container) in config.json. Off by default to avoid leaking local "
        "paths/usernames into published runs.",
    )
    args = parser.parse_args(argv)

    cfg = load_config(args.config)
    if args.name:
        cfg.name = args.name
    if args.run_group is not None:
        cfg.run_group = args.run_group
    if args.seeds is not None:
        cfg.n_seeds = args.seeds
    if args.queries:
        cfg.queries = args.queries.split()
    if args.rewards:
        cfg.reward_modes = args.rewards.split()
    if args.aggs:
        cfg.uct_aggregations = args.aggs.split()
    if args.configs:
        cfg.configs = args.configs.split()
    if args.measurement is not None:
        cfg.measurement = args.measurement
    if cfg.measurement == "cost_only":
        cfg.n_seeds = 1

    cli_gucs = json.loads(args.gucs)
    if args.mcts_cells is not None:
        cfg.mcts_cells = json.loads(args.mcts_cells)
    if args.source:
        cfg.sources = parse_sources(args.source)
    if args.docker_container is not None:
        cfg.docker_container = args.docker_container
    if args.pguser is not None:
        cfg.pguser = args.pguser

    for src in cfg.sources:
        d = resolve_source_dir(src)
        if not d.is_dir():
            print(f"source directory not found: {d} (source={src!r})", file=sys.stderr)
            return 2
    query_paths: dict[str, Path] = {}
    for q in cfg.queries:
        p = find_query_source(q, cfg.sources)
        if p is None:
            print(f"missing query {q!r} in any source ({', '.join(cfg.sources)})", file=sys.stderr)
            return 3
        query_paths[q] = p

    selected_cells = _selected_mcts_cells(cfg) if cfg.mcts_cells else []
    if selected_cells:
        combos = [cell[-1] for cell in selected_cells]
        varying = []
        combo_ids = [cell[3] for cell in selected_cells]
    else:
        combos, varying = expand_gucs_grid(cli_gucs)
        combo_ids = [combo_id(c, varying) for c in combos]

    # MCTS configs span reward × agg × combo; baselines emit one cell per query
    # with sentinel "n/a" reward/agg + empty combo so the row schema stays uniform.
    cells: list[tuple[str, str, str, str, dict]] = []
    for config in cfg.configs:
        if config in BASELINE_CONFIGS:
            cells.append((config, "n/a", "n/a", "", {}))
        elif selected_cells:
            cells.extend([cell for cell in selected_cells if cell[0] == config])
        else:
            for reward in cfg.reward_modes:
                for agg in cfg.uct_aggregations:
                    for combo, cid in zip(combos, combo_ids, strict=False):
                        cells.append((config, reward, agg, cid, combo))
    total_cells = len(cells) * len(cfg.queries)
    total_runs = total_cells * cfg.n_seeds

    if args.dry_run:
        print(f"Experiment:    {cfg.name}")
        print(f"Queries ({len(cfg.queries)}): {' '.join(cfg.queries)}")
        if varying:
            print(f"Grid:          {len(combos)} combos varying {['.'.join(p) for p in varying]}")
        if selected_cells:
            print(f"Selected MCTS: {len(selected_cells)} cells")
        print(
            f"Cells ({len(cells)}): "
            + ", ".join(lib.short_label(c, r, a, cid) for c, r, a, cid, _ in cells)
        )
        print(f"Seeds:         {cfg.n_seeds}")
        print(f"Total cells:   {total_cells}")
        print(f"Total runs:    {total_runs}")
        ts = dt.datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
        print(f"Run dir (preview): {args.runs_root}/{ts}-{cfg.name}")
        return 0

    if not cfg.docker_container and not cfg.pgdata:
        print(
            "PGDATA is not set — point it at your Postgres data dir.\n"
            "  PGDATA=/path/to/data PGBIN=/path/to/bin uv run sweep.py ...\n"
            "or use --docker-container <name> for Docker-backed runs.\n"
            "(PGBIN is optional if pg_ctl is on PATH.)",
            file=sys.stderr,
        )
        return 4
    if not cfg.docker_container and not Path(cfg.pgdata).is_dir():
        print(f"PGDATA does not exist: {cfg.pgdata}", file=sys.stderr)
        return 4

    # Fail fast within the UI's 1.2s launch-error window: if PG isn't reachable,
    # auto-start it; if startup fails, surface the real reason instead of letting
    # restart_cluster blow up mid-sweep with a buried errors.log.
    if not ensure_pg_running(cfg):
        return 5

    args.runs_root.mkdir(parents=True, exist_ok=True)
    run_dir, _combos2, _varying2 = init_run_dir(cfg, cli_gucs, args.runs_root, record_env=args.record_env)
    print(f"Run dir: {run_dir}", file=sys.stderr)
    print(
        f"Sweep plan: {len(cfg.queries)} queries x {len(cells)} cells x "
        f"{cfg.n_seeds} seeds = {total_runs} runs "
        f"(grid: {len(combos)} combos, varying={['.'.join(p) for p in varying]})",
        file=sys.stderr,
    )

    (run_dir / "pid").write_text(str(os.getpid()) + "\n")

    # SIGTERM/SIGINT → KeyboardInterrupt so the except-block flips status to "stopped".
    def _on_signal(signum, frame):
        raise KeyboardInterrupt(f"signal {signum}")

    signal.signal(signal.SIGTERM, _on_signal)
    signal.signal(signal.SIGINT, _on_signal)

    results_path = run_dir / "results.jsonl"

    config_sqlfile: dict[tuple[str, str], Path] = {}
    for cid in combo_ids:
        config_sqlfile[("luby", cid)] = run_dir / _sql_basename("luby", cid)
        config_sqlfile[("single", cid)] = run_dir / _sql_basename("single", cid)
    for bname in BASELINE_CONFIGS:
        p = run_dir / f"{bname}.sql"
        if p.exists():
            config_sqlfile[(bname, "")] = p

    tmpdir = Path(tempfile.mkdtemp(prefix="mcts_sweep."))
    measure_paths: dict[str, Path] = {
        q: build_measure_sql(query_paths[q], q, tmpdir, cfg.measurement) for q in cfg.queries
    }
    prewarm_paths: dict[str, Path] = {
        q: build_prewarm_sql(query_paths[q], q, tmpdir) for q in cfg.queries
    }
    query_source_name: dict[str, str] = {}
    for q in cfg.queries:
        p = query_paths[q]
        matched = next(
            (s for s in cfg.sources if resolve_source_dir(s).resolve() == p.parent.resolve()),
            p.parent.name,
        )
        query_source_name[q] = matched

    # Pre-create every cell dir up front so concurrent workers don't race on mkdir.
    for config, reward, agg, cid, _ in cells:
        for q in cfg.queries:
            (run_dir / cell_dirname(config, reward, agg, cid) / q).mkdir(
                parents=True, exist_ok=True
            )

    # Parallelism cap.  0 (default) = one worker per cell.  Barrier-synchronized launch
    # is only safe when workers == len(cells); otherwise workers run FIFO and we skip it.
    max_workers = args.parallel if args.parallel > 0 else len(cells)
    max_workers = max(1, min(max_workers, len(cells)))
    if args.clean_per_run:
        max_workers = 1
    use_barrier = max_workers == len(cells) and len(cells) > 1
    prewarm_enabled = args.prewarm
    clean_scope = "run" if args.clean_per_run else "batch"

    print(
        f"Run mode: workers={max_workers}/{len(cells)} cells, "
        f"clean_scope={clean_scope}, "
        f"restart_pg={'on' if args.restart_pg_per_batch else 'off'}, "
        f"prewarm={'on' if prewarm_enabled else 'off'}, "
        f"drop_os_cache={'on' if args.drop_os_cache else 'off'}, "
        f"barrier={'on' if use_barrier else 'off'}, "
        f"backend={'docker:' + cfg.docker_container if cfg.docker_container else 'local'}",
        file=sys.stderr,
    )

    total_batches = len(cfg.queries) * cfg.n_seeds
    batch_idx = 0
    started = time.time()

    def _clean_environment(q: str | None = None) -> None:
        if args.restart_pg_per_batch:
            try:
                restart_cluster(cfg)
            except subprocess.CalledProcessError as e:
                print(f"cluster restart failed: {e}", file=sys.stderr)
                raise
        time.sleep(0.3)

        if args.drop_os_cache:
            try:
                drop_os_caches(args.drop_cache_command)
            except subprocess.CalledProcessError as e:
                stderr = (e.stderr or "").strip()
                print(
                    "OS cache drop failed. Configure passwordless sudo for "
                    f"{DEFAULT_DROP_CACHES} or pass --drop-cache-command. "
                    f"rc={e.returncode}"
                    + (f"\nstderr: {stderr}" if stderr else ""),
                    file=sys.stderr,
                )
                raise

        if prewarm_enabled and q is not None:
            run_prewarm(cfg, prewarm_paths[q])

    def _measure_cell(
        cell: tuple[str, str, str, str, dict],
        q: str,
        seed: int,
        barrier: threading.Barrier | None,
    ) -> dict:
        config, reward, agg, cid, combo = cell
        sqlfile = config_sqlfile.get((config, cid if config not in BASELINE_CONFIGS else ""))
        if sqlfile is None:
            raise ValueError(f"no SQL template for config {config!r} combo {cid!r}")
        if barrier is not None:
            barrier.wait()
        if args.clean_per_run:
            print(
                f"  clean+run {q} seed={seed} "
                f"{lib.short_label(config, reward, agg, cid)}",
                file=sys.stderr,
            )
            _clean_environment(q)
        out = run_psql(
            cfg,
            sqlfile,
            reward=reward,
            agg=agg,
            seed=seed,
            query_sql=measure_paths[q],
        )
        plan_path = run_dir / cell_dirname(config, reward, agg, cid) / q / f"seed-{seed}.plan"
        plan_path.write_text(out)
        parsed = lib.parse_explain(out)
        return {
            "ts": dt.datetime.now().isoformat(timespec="milliseconds") + "Z",
            "query": q,
            "source": query_source_name.get(q, ""),
            "config": config,
            "reward": reward,
            "agg": agg,
            "combo_id": cid,
            "gucs": combo,
            "measurement": cfg.measurement,
            "seed": seed,
            **parsed,
            "plan_path": str(plan_path.relative_to(run_dir)),
        }

    try:
        for q in cfg.queries:
            for seed in range(1, cfg.n_seeds + 1):
                batch_idx += 1
                elapsed = int(time.time() - started)
                print(
                    f"[batch {batch_idx}/{total_batches}  elapsed {elapsed}s] "
                    f"query={q} seed={seed} cells={len(cells)}",
                    file=sys.stderr,
                )

                if not args.clean_per_run:
                    _clean_environment(q)

                if args.clean_per_run:
                    for cell in cells:
                        append_jsonl(results_path, _measure_cell(cell, q, seed, None))
                    continue

                barrier = threading.Barrier(len(cells)) if use_barrier else None
                # Preserve deterministic write order by indexing results to their cell slot.
                rows: list[dict | None] = [None] * len(cells)
                with cf.ThreadPoolExecutor(max_workers=max_workers) as ex:
                    futures = {
                        ex.submit(_measure_cell, cell, q, seed, barrier): i
                        for i, cell in enumerate(cells)
                    }
                    for fut in cf.as_completed(futures):
                        rows[futures[fut]] = fut.result()
                for row in rows:
                    if row is not None:
                        append_jsonl(results_path, row)

        lib.write_status(run_dir, lib.STATUS_DONE)
        print("Done.", file=sys.stderr)
        return 0

    except KeyboardInterrupt:
        lib.write_status(run_dir, lib.STATUS_STOPPED)
        (run_dir / "errors.log").write_text("interrupted\n")
        print("interrupted", file=sys.stderr)
        return 130
    except Exception as e:
        lib.write_status(run_dir, lib.STATUS_FAILED)
        import traceback

        (run_dir / "errors.log").write_text(traceback.format_exc())
        print(f"FAILED: {e}", file=sys.stderr)
        return 1
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
        # Remove pid file so the UI knows the process is gone.
        with contextlib.suppress(FileNotFoundError):
            (run_dir / "pid").unlink()


if __name__ == "__main__":
    sys.exit(main())
